name: Bug Report
description: Something isn't working
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Minimal code or steps to reproduce
      placeholder: |
        ```ts
        import { chunk } from 'code-chunk'
        // ...
        ```
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 1.0.0
    validations:
      required: false
